---
- hosts: web

  tasks:
    - name: Install nodejs
      apt: pkg='nodejs' state='present'
    - name: Install MongoDB
      apt: pkg='mongodb' state='present'

    - name: Define Environment variables
      environment:
        APP_PORT: 3002
        MONGO_PORT: 27017
        MONGO_USER: <user>
        MONGO_PASSWORD: <pass> 
        MONGO_IP: localhost