---
- name: Add nodejs apt key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: Add nodejs 14.x ppa for apt repo
  apt_repository:
    repo: 'deb https://deb.nodesource.com/node_14.x focal main'
    update_cache: yes

- name: Install nodejs
  apt: 
    pkg: nodejs
    state: present

- name: Add Java Repository
  apt_repository:
    repo: 'ppa:openjdk-r/ppa'
    state: present

- name: Install Java
  apt:
    pkg: openjdk-11-jdk
    state: present
    update_cache: yes

- name: Install Maven
  apt:
    pkg: maven
    state: latest
    update_cache: yes

- name: Install MySQL and related packages
  apt: 
    name: ['mysql-server', 'mysql-client']
    state: present

- name: Start MySQL service
  service: 
    name: mysql
    state: started
    enabled: true

- name: Create .my.cnf file with root user credentials
  template: 
    src: /bakerx/my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: 0600
  notify:
  - Restart MySQL

- name: Install Chrome
  apt:
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

- name: Add tomcat group
  group:
    name: tomcat

- name: Add "tomcat" user
  user:
    name: tomcat
    group: tomcat
    home: /usr/share/tomcat
    createhome: no
    system: yes

- name: Create Tomcat Directory
  file:
    path: /usr/share/tomcat
    state: directory
    owner: tomcat
    group: tomcat

- name: Download Tomcat
  get_url:
    url: "https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.45/bin/apache-tomcat-9.0.45.tar.gz"
    dest: /tmp/apache-tomcat-9.0.45.tar.gz

- name: extract tomcat packages
  unarchive:
    src: /tmp/apache-tomcat-9.0.45.tar.gz
    dest: /usr/share/tomcat
    remote_src: yes
    extra_opts: "--strip-components=1"
    creates: /usr/share/tomcat/bin

- name: Copy tomcat service file
  ansible.builtin.copy:
    src: /bakerx/cm/roles/itrustEnvironment/templates/tomcat.service
    dest: /etc/systemd/system/

- name: Copy tomcat users file
  ansible.builtin.copy:
    src: /bakerx/cm/roles/itrustEnvironment/templates/tomcat-users.xml
    dest: /usr/share/tomcat/conf/

- name: Initialize Tomcat
  script: /bakerx/cm/tomcat-init.sh

- name: copy WAR file
  ansible.builtin.copy:
    src: /var/lib/jenkins/userContent/iTrust2.war
    dest: /usr/share/tomcat/webapps/
    
- name: Restart Tomcat
  script: /bakerx/cm/tomcat-restart.sh
