---
- name: start MongoDB if not already running
  service:
    name=mongod
    state=started
    enabled=yes

- name: Install npm pm2 package
  npm:
    name: pm2
    global: yes

- name: Git checkout
  git:
    repo: 'https://github.com/chrisparnin/checkbox.io'
    dest: ./checkbox.io

# sudo pip3 install ansible-modules-pm2  needs to be added to config-srv
- name: Start checkbox.io, if not running
  pm2:
    name: checkbox.io
    script: ./checkbox.io/server-side/site/server.js
    state: started