---
- name: Add nodejs apt key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: Add nodejs 14.x ppa for apt repo
  apt_repository:
    repo: 'deb https://deb.nodesource.com/node_14.x focal main'
    update_cache: yes

- name: Install nodejs
  apt: 
    pkg: nodejs
    state: present

- name: Import MongoDB public key
  apt_key: 
    url: https://www.mongodb.org/static/pgp/server-4.4.asc
    state: present

- name: Add MongoDB Repository
  apt_repository: 
    repo: 'deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse'
    state: present

- name: Install MongoDB
  apt: 
    pkg: mongodb-org
    state: latest
    update_cache: yes
  notify: 
  - Start mongodb

- name: Install pymongo through pip
  pip:
    name: pymongo

- name: Flush Handlers
  meta: flush_handlers

- name: Create mongo user
  mongodb_user:
    database: admin
    name: mongo
    password: '{{ vault_db_mongo_password }}'
    roles: readWrite
    state: present

- name: Define Environment variables
  lineinfile:
    path: /etc/environment
    line: '{{ item }}'
    state: present
  with_items:
    - APP_PORT=3002
    - MONGO_PORT=27017
    - MONGO_USER="mongo"
    - MONGO_PASSWORD="{{ vault_db_mongo_password }}"
    - MONGO_IP="localhost"
    - MYSQL_PASSWORD="{{ vault_db_mysql_root_password }}"

- name: Add Java Repository
  apt_repository:
    repo: 'ppa:openjdk-r/ppa'
    state: present

- name: Install Java
  apt:
    pkg: openjdk-11-jdk
    state: present
    update_cache: yes

- name: Install Maven
  apt:
    pkg: maven
    state: latest
    update_cache: yes

- name: Install MySQL and related packages
  apt: 
    name: ['mysql-server', 'mysql-client']
    state: present

- name: Install PyMySQL
  pip:
    name: pymysql
    state: present

- name: Install ansible pm2 module
  pip:
    name: ansible-modules-pm2
    state: present

- name: Start MySQL service
  service: 
    name: mysql
    state: started
    enabled: true

# See the notes here for an explanation of why this is necessary:
# https://docs.ansible.com/ansible/latest/collections/community/mysql/mysql_user_module.html#notes
- name: Set MySQL root Password
  mysql_user:
    name: root
    password: "{{ vault_db_mysql_root_password }}"
    check_implicit_admin: true
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create .my.cnf file with root user credentials
  template: 
    src: /bakerx/my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: 0600
  notify:
  - Restart MySQL

- name: Install jq to be used in building Jenkins credentials request
  apt:
    pkg: jq
    state: present

- name: Install Chrome
  apt:
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

- name: Create target directory for ansible.cfg file
  file:
    path: /etc/ansible
    state: directory

- name: Copy ansible.cfg file
  template:
    src: /bakerx/ansible.cfg
    dest: /etc/ansible/ansible.cfg
