---
- name: Add nodejs apt key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: Add nodejs 14.x ppa for apt repo
  apt_repository:
    repo: 'deb https://deb.nodesource.com/node_14.x focal main'
    update_cache: yes

- name: Install nodejs
  apt: 
    pkg: nodejs
    state: present

- name: Import MongoDB public key
  apt_key: 
    url: https://www.mongodb.org/static/pgp/server-4.4.asc
    state: present

- name: Add MongoDB Repository
  apt_repository: 
    repo: 'deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse'
    state: present

- name: Install MongoDB
  apt: 
    pkg: mongodb-org
    state: latest
    update_cache: yes
  notify: 
  - Start mongodb

- name: Install pymongo through pip
  pip:
    name: pymongo

- name: Flush Handlers
  meta: flush_handlers

- name: Create mongo user
  mongodb_user:
    database: admin
    name: mongo
    password: '{{ vault_db_mongo_password }}'
    roles: readWrite
    state: present

- name: Define Environment variables
  lineinfile:
    path: /etc/environment
    line: '{{ item.key }}'
    state: present
  with_items:
    - { key: 'APP_PORT=3002' }
    - { key: 'MONGO_PORT=27017' }
    - { key: 'MONGO_USER="mongo"' }
    - { key: 'MONGO_PASSWORD="{{ vault_db_mongo_password }}"'}
    - { key: 'MONGO_IP="localhost"' }

- name: Add Java Repository
  apt_repository:
    repo: 'ppa:openjdk-r/ppa'
    state: present

- name: Install Java
  become: yes
  apt:
    pkg: openjdk-8-jdk
    state: present
    update_cache: yes

- name: Install Maven
  become: yes
  apt:
    pkg: maven
    state: latest
    update_cache: yes
