--- # Based on Jenkins documentation: https://www.jenkins.io/doc/book/installing/linux/#debianubuntu
- name: Add jenkins repository key
  apt_key:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
    state: present

- name: Append package repository to sources.list
  apt_repository:
    repo: 'deb http://pkg.jenkins-ci.org/debian-stable binary/'
    state: present
    
- name: Install Jenkins
  apt:
    name: jenkins
    state: present
  notify: Restart Jenkins

- name: Turn off Jenkins setup wizard
  lineinfile:
    dest: /etc/default/jenkins
    regexp: '^JAVA_ARGS='
    line: 'JAVA_ARGS="-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false"'
  notify: Restart Jenkins

- name: Update port number for Jenkins to 9000
  lineinfile:
    path: /etc/default/jenkins
    regexp: '^HTTP_PORT=8080$'
    line: 'HTTP_PORT=9000'
    backrefs: yes
  notify: Restart Jenkins

- name: Create target directory for Groovy security script
  file:
    path: /var/lib/jenkins/init.groovy.d
    state: directory
    owner: jenkins
    group: jenkins
    mode: 0755

- name: Save Jenkins admin password to environment
  lineinfile:
    path: /etc/environment
    line: 'JENKINS_ADMIN_PASSWORD="{{ vault_jenkins_admin_password }}"'
    state: present

# Code is taken from example provided in Discord
- name: Copy a Groovy file to configure admin user
  template:
    src: /bakerx/groovy-security-script
    dest: /var/lib/jenkins/init.groovy.d/basic-security.groovy
  notify: Restart Jenkins

# Trigger restart before installing plugins
# See https://docs.ansible.com/ansible/latest/user_guide/playbooks_handlers.html#controlling-when-handlers-run
- name: Flush handlers to trigger Jenkins restart
  meta: flush_handlers

- name: Install Jenkins plugins
  jenkins_plugin:
    name: '{{ item }}'
    url: http://192.168.33.20:9000/
    url_username: admin
    url_password: '{{ vault_jenkins_admin_password }}'
    timeout: 120
  notify: Restart Jenkins
  with_items:
    - 'workflow-aggregator'
    - 'git'
    - 'ws-cleanup'
    - 'pipeline-stage-view'
    - 'warnings-ng'
    - 'jacoco'

# Trigger restart after installing plugins
- name: Flush handlers to trigger Jenkins restart
  meta: flush_handlers
