- job:
    name: checkio-build-job
    project-type: pipeline
    dsl: |
      node {
          stage('Source') {
              git 'https://github.com/chrisparnin/checkbox.io'
          }
          stage('Build') {
              sh 'npm install --prefix ./server-side/site'
              sh 'cd ./server-side/site/ ; npm start &'
          }
          stage('Test') {
              sh 'cd ./server-side/site/ ; npm test'
          }
      }
      
