--- # Based on Jenkins documentation: https://www.jenkins.io/doc/book/installing/linux/#debianubuntu
- name: Make sure open jdk is installed
  apt:
    name: openjdk-11-jdk
    state: latest
    install_recommends: no

- name: Make sure wget is installed
  apt:
    name: wget
    state: present

- name: Add jenkins repository key
  apt_key:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
    state: present

- name: Append package repository to sources.list
  apt_repository:
    repo: 'deb http://pkg.jenkins-ci.org/debian-stable binary/'
    state: present
    
- name: Install Jenkins
  apt:
    name: jenkins
    state: present
  notify: Restart Jenkins

- name: Turn off Jenkins setup wizard
  lineinfile:
    dest: /etc/default/jenkins
    regexp: '^JAVA_ARGS='
    line: 'JAVA_ARGS="-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false"'
  notify: Restart Jenkins

- name: Update port number for Jenkins to 9000
  lineinfile:
    path: /etc/default/jenkins
    regexp: '^HTTP_PORT=8080$'
    line: 'HTTP_PORT=9000'
    backrefs: yes
  notify: Restart Jenkins

- name: Create target directory for Groovy security script
  file:
    path: /var/lib/jenkins/init.groovy.d
    state: directory
    owner: jenkins
    group: jenkins
    mode: 0755

# Code is taken from example provided in Discord
- name: Copy a Groovy file to configure admin user
  template:
    src: /bakerx/groovy-security-script
    dest: /var/lib/jenkins/init.groovy.d/basic-security.groovy
  notify: Restart Jenkins

# Trigger restart before installing plugins
# See https://docs.ansible.com/ansible/latest/user_guide/playbooks_handlers.html#controlling-when-handlers-run
- name: Flush handlers to trigger Jenkins restart
  meta: flush_handlers

- name: Install Jenkins plugins
  jenkins_plugin:
    name: '{{ item.key }}'
    url: http://192.168.33.20:9000/
    url_username: admin
    url_password: admin
    timeout: 120
  notify: Restart Jenkins
  with_items:
    - { key: 'workflow-aggregator' }
    - { key: 'git' }
    - { key: 'ws-cleanup' }
    - { key: 'pipeline-stage-view' }

# Trigger restart after installing plugins
- name: Flush handlers to trigger Jenkins restart
  meta: flush_handlers
    
- name: Install nodejs
  apt: pkg='nodejs' state='present'
    
- name: Install MongoDB
  apt: pkg='mongodb' state='present'

- name: Install Jenkins Job Builder
  apt:
    name: jenkins-job-builder
    state: present

#- name: Run Build Job - checkbox.io
#  shell: 'jenkins-jobs --conf /bakerx/cm/jenkins_jobs.ini update /bakerx/cm/roles/jenkins/tasks/create-build-job-checkpoint-io.yml'

- name: Install npm
  apt: pkg='npm' state='present'

- name: start MongoDB if not already running
  service:
    name=mongodb
    state=started
    enabled=yes

# Deprecated. These commands can be used to create and start the checkbox.io build job using Jenkins-cli during pipeline setup.
#- name: Create Build Job XML with JJB - checkbox.io
#  shell: jenkins-jobs test -o ./ /bakerx/cm/roles/jenkins/tasks/create-build-job-checkpoint-io.yml
  
#- name: Create Build Job - checkbox.io
#  shell: java -jar /bakerx/jenkins-cli.jar -s http://admin:admin@192.168.33.20:9000/ create-job checkio-build-job<./checkio-build-job

#- name: Run Build Job - checkbox.io
#  shell: java -jar /bakerx/jenkins-cli.jar -s http://admin:admin@192.168.33.20:9000/ build checkio-build-job
